// Generated by tools/demo-build.mjs — the lint-checked twin of index.html.
// The class strings are identical to the shipped page, so a finding here is
// a finding about the page you are looking at.
export function Page() {
  return (
    <div className="bg-neutral-900 text-ink-default font-body antialiased">
      <nav className="border-neutral-700 bg-neutral-800 border-b">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="font-heading text-primary-900 text-lg font-bold">Arena Rank</div>
          <div className="hidden gap-6 md:flex">
            <a className="text-ink-muted hover:text-ink-default text-sm" href="#features">Features</a>
            <a className="text-ink-muted hover:text-ink-default text-sm" href="#pricing">Pricing</a>
            <a className="text-ink-muted hover:text-ink-default text-sm" href="#components">Components</a>
            <a className="text-ink-muted hover:text-ink-default text-sm" href="#story">Story</a>
          </div>
          <a className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-3 py-1 text-xs" href="#pricing">Analyse a replay</a>
        </div>
      </nav>
      
      <div className="mx-auto max-w-6xl px-6 pt-6">
        <div className="flex items-start gap-3 rounded-md border border-info-600 bg-neutral-800 p-4 " role="status">
        <svg className="mt-0.5 h-4 w-4 shrink-0 text-ink-muted" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1.4"/>
          <path d="M8 7.5v4M8 5h.01" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Competitive coaching</p>
          <p className="mt-1 text-sm text-ink-muted">Arena Rank is live — 1.8M replays analysed and counting.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-ink-subtle hover:bg-neutral-700" type="button" aria-label="Dismiss">✕</button>
      </div>
      </div>
      
      <header className="mx-auto max-w-6xl px-6 py-16 text-center">
        <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-info-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Competitive coaching</span>
        <h1 className="font-heading text-ink-default mt-6 text-4xl font-extrabold leading-tight md:text-6xl">
          Climb the ladder<br/><span className="text-primary-900">with evidence</span>
        </h1>
        <p className="text-ink-muted mx-auto mt-6 max-w-2xl text-lg">Replay analysis, coaching and team tools for players who want to improve, not just play more.</p>
        <form className="mx-auto mt-8 flex max-w-md flex-col gap-3 sm:flex-row" onsubmit="return false">
          <div className="flex-1 text-left">
        
        <input className="w-full rounded-md border bg-neutral-800 px-3 py-2 text-sm text-ink-default placeholder:text-ink-subtle border-neutral-600" id="hero-email" type="email" placeholder="you@company.com"/>
        
      </div>
          <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-4 py-2 text-sm shrink-0" type="button">Analyse a replay</button>
        </form>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
          <div className="flex items-center">
            <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-8 w-8 text-xs" title="Amelia R.">AR</span>
          <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-8 w-8 text-xs -ml-2" title="Thabo K.">TK</span>
          <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-8 w-8 text-xs -ml-2" title="Marta S.">MS</span>
          <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-8 w-8 text-xs -ml-2" title="Jonas B.">JB</span>
          <span className="-ml-2 inline-flex h-8 w-8 text-xs items-center justify-center rounded-full border-2 border-neutral-900 bg-neutral-700 text-ink-muted">+12</span>
          </div>
          <p className="text-ink-subtle text-sm">Trusted by 1.8M replays analysed</p>
        </div>
      </header>
      
      <section className="border-y border-neutral-700 bg-neutral-800 border-b">
        <div className="mx-auto grid max-w-6xl grid-cols-2 gap-8 px-6 py-12 md:grid-cols-4">
          <div className="text-center"><div className="font-heading text-primary-900 text-3xl font-extrabold">1.8M</div><div className="text-ink-subtle mt-2 text-sm">Replays analysed</div></div>
          <div className="text-center"><div className="font-heading text-primary-900 text-3xl font-extrabold">620</div><div className="text-ink-subtle mt-2 text-sm">Verified coaches</div></div>
          <div className="text-center"><div className="font-heading text-primary-900 text-3xl font-extrabold">+180</div><div className="text-ink-subtle mt-2 text-sm">Avg. rating gain</div></div>
          <div className="text-center"><div className="font-heading text-primary-900 text-3xl font-extrabold">9</div><div className="text-ink-subtle mt-2 text-sm">Titles supported</div></div>
        </div>
      </section>
      
      <section id="features" className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="font-heading text-ink-default text-center text-3xl font-bold">Everything you need</h2>
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6 transition-colors"><h3 className="font-heading text-ink-default text-lg font-semibold">Replay analysis</h3>
              <p className="text-ink-muted mt-3 text-sm leading-relaxed">Upload a match, get timestamped decisions handed back.</p></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6 transition-colors"><h3 className="font-heading text-ink-default text-lg font-semibold">Verified coaches</h3>
              <p className="text-ink-muted mt-3 text-sm leading-relaxed">Rank-checked and reviewed before they can take bookings.</p></article>
          <article className="rounded-lg border border-neutral-600 p-6 transition-colors"><h3 className="font-heading text-ink-default text-lg font-semibold">Team tools</h3>
              <p className="text-ink-muted mt-3 text-sm leading-relaxed">Shared VOD review, drills and a practice schedule.</p></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6 transition-colors"><h3 className="font-heading text-ink-default text-lg font-semibold">Progress tracking</h3>
              <p className="text-ink-muted mt-3 text-sm leading-relaxed">See the specific thing you improved, not just a number.</p></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6 transition-colors"><h3 className="font-heading text-ink-default text-lg font-semibold">Draft helper</h3>
              <p className="text-ink-muted mt-3 text-sm leading-relaxed">Composition and counter-pick data, updated weekly.</p></article>
          <article className="rounded-lg border border-neutral-600 p-6 transition-colors"><h3 className="font-heading text-ink-default text-lg font-semibold">Scrim finder</h3>
              <p className="text-ink-muted mt-3 text-sm leading-relaxed">Match with teams at your level in under five minutes.</p></article>
        </div>
      </section>
      
      <section id="glance" className="border-neutral-700 bg-neutral-800">
        <div className="mx-auto max-w-6xl px-6 py-20">
          <h2 className="font-heading text-ink-default text-center text-3xl font-bold">At a glance</h2>
          <p className="text-ink-muted mx-auto mt-4 max-w-2xl text-center text-sm">Live numbers, rendered with the data-table component.</p>
          <div className="mt-10">
            <div className="overflow-hidden rounded-lg border border-neutral-700">
        <table className="w-full border-collapse">
          <caption className="sr-only">Arena Rank at a glance</caption>
          <thead className="bg-neutral-800">
            <tr>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Metric</th>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Value</th>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Period</th>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted">Replays analysed</td>
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">1.8M</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Last 30 days</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Healthy</span></td>
            </tr>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted">Verified coaches</td>
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">620</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Last 30 days</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Healthy</span></td>
            </tr>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted">Avg. rating gain</td>
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">+180</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Last 30 days</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Healthy</span></td>
            </tr>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted">Titles supported</td>
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">9</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Last 30 days</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Healthy</span></td>
            </tr>
          </tbody>
        </table>
      </div>
          </div>
        </div>
      </section>
      
      <section id="pricing" className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="font-heading text-ink-default text-center text-3xl font-bold">Simple, transparent pricing</h2>
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          <article className="rounded-lg border border-neutral-600 p-6"><div className="flex items-start justify-between">
              <h3 className="font-heading text-ink-default text-lg font-semibold">Free</h3>
              <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-neutral-700 text-ink-muted ">Free</span>
            </div>
            <div className="font-heading text-ink-default mt-4 text-4xl font-extrabold">$0</div>
            <ul className="mt-6 space-y-2">
              <li className="text-ink-muted text-sm">— 10 analyses / month</li>
              <li className="text-ink-muted text-sm">— Basic stats</li>
              <li className="text-ink-muted text-sm">— Community access</li>
            </ul>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity border border-neutral-600 text-ink-default hover:bg-neutral-700 px-4 py-2 text-sm mt-8 w-full" type="button">Choose Free</button></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6 border border-primary-900"><div className="flex items-start justify-between">
              <h3 className="font-heading text-ink-default text-lg font-semibold">Ranked</h3>
              <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Most popular</span>
            </div>
            <div className="font-heading text-ink-default mt-4 text-4xl font-extrabold">$12/mo</div>
            <ul className="mt-6 space-y-2">
              <li className="text-ink-muted text-sm">— Unlimited analyses</li>
              <li className="text-ink-muted text-sm">— Draft helper</li>
              <li className="text-ink-muted text-sm">— Progress tracking</li>
            </ul>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-4 py-2 text-sm mt-8 w-full" type="button">Choose Ranked</button></article>
          <article className="rounded-lg border border-neutral-600 p-6"><div className="flex items-start justify-between">
              <h3 className="font-heading text-ink-default text-lg font-semibold">Team</h3>
              <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-neutral-700 text-ink-muted ">Team</span>
            </div>
            <div className="font-heading text-ink-default mt-4 text-4xl font-extrabold">$49/mo</div>
            <ul className="mt-6 space-y-2">
              <li className="text-ink-muted text-sm">— 6 members</li>
              <li className="text-ink-muted text-sm">— Team tools</li>
              <li className="text-ink-muted text-sm">— Scrim finder</li>
              <li className="text-ink-muted text-sm">— Shared review</li>
            </ul>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity border border-neutral-600 text-ink-default hover:bg-neutral-700 px-4 py-2 text-sm mt-8 w-full" type="button">Choose Team</button></article>
        </div>
      </section>
      
      <section id="story" className="mx-auto max-w-3xl px-6 py-20">
        <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-8 text-center"><blockquote className="font-heading text-ink-default text-2xl font-semibold leading-snug">“It told me I was losing every fight at 40 seconds. I did not believe it until I watched the reel.”</blockquote>
          <div className="mt-6 flex items-center gap-3">
            <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 h-10 w-10 text-sm" title="K. Tanaka · Diamond II">KT</span>
            <p className="text-ink-subtle text-sm">K. Tanaka · Diamond II</p>
          </div></article>
      </section>
      
      <section className="border-neutral-700 bg-neutral-800">
        <div className="mx-auto max-w-4xl px-6 py-20 text-center">
          <h2 className="font-heading text-ink-default text-3xl font-bold">Ready to start?</h2>
          <p className="text-ink-muted mx-auto mt-4 max-w-xl">Find a coach — no card, no call, no commitment.</p>
          <div className="mt-8 flex flex-wrap justify-center gap-4">
            <a className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-6 py-3 text-base" href="#pricing">Analyse a replay</a>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity border border-neutral-600 text-ink-default hover:bg-neutral-700 px-6 py-3 text-base" type="button">Talk to us</button>
          </div>
        </div>
      </section>
      
      <section id="components" className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="font-heading text-center text-3xl font-bold text-ink-default">Every component, in this system's tokens</h2>
        <p className="mx-auto mt-4 max-w-2xl text-center text-sm text-ink-muted">The eight components shipped by DesignOps, rendered with this page's own tokens. They are not a bolted-on appendix — the page above is built from them, and this is the full set with every variant.</p>
        <div className="mt-12 grid gap-6 lg:grid-cols-2">
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Button</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Four variants, three sizes, plus the disabled state.</p>
            <div className="flex flex-col gap-4">
          <div className="flex flex-wrap items-center gap-3">
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-4 py-2 text-sm" type="button">Primary</button>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity border border-neutral-600 text-ink-default hover:bg-neutral-700 px-4 py-2 text-sm" type="button">Secondary</button>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-danger-600 text-neutral-900 hover:bg-danger-600 px-4 py-2 text-sm" type="button">Destructive</button>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity text-ink-muted hover:bg-neutral-700 px-4 py-2 text-sm" type="button">Ghost</button>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-4 py-2 text-sm opacity-50" type="button" disabled="">Disabled</button>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-3 py-1 text-xs" type="button">Small</button>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-4 py-2 text-sm" type="button">Medium</button>
            <button className="inline-flex items-center justify-center gap-2 rounded-md font-medium transition-opacity bg-primary-900 text-neutral-900 hover:bg-primary-800 px-6 py-3 text-base" type="button">Large</button>
          </div>
        </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Input Field</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Labels, hints, the error state and a disabled field.</p>
            <div className="grid gap-4 md:grid-cols-2">
          <div className="">
        <label className="block text-xs font-medium text-ink-muted mb-1" for="cs-email">Email</label>
        <input className="w-full rounded-md border bg-neutral-800 px-3 py-2 text-sm text-ink-default placeholder:text-ink-subtle border-neutral-600" id="cs-email" type="email" placeholder="you@example.com" aria-describedby="cs-email-note"/>
        <p className="mt-1 text-xs text-ink-subtle" id="cs-email-note">We only use this to send the receipt.</p>
      </div>
          <div className="">
        <label className="block text-xs font-medium text-ink-muted mb-1" for="cs-error">Card number</label>
        <input className="w-full rounded-md border bg-neutral-800 px-3 py-2 text-sm text-ink-default placeholder:text-ink-subtle border-danger-600" id="cs-error" type="text" value="4242 4242" aria-describedby="cs-error-note"/>
        <p className="mt-1 text-xs text-danger-600" id="cs-error-note">That card number is not valid.</p>
      </div>
          <div className="">
        <label className="block text-xs font-medium text-ink-muted mb-1" for="cs-disabled">Promo code</label>
        <input className="w-full rounded-md border bg-neutral-800 px-3 py-2 text-sm text-ink-default placeholder:text-ink-subtle border-neutral-600 opacity-50" id="cs-disabled" type="text" placeholder="Not available" disabled=""/>
        
      </div>
          <div className="">
        <label className="block text-xs font-medium text-ink-muted mb-1" for="cs-required">Workspace name *</label>
        <input className="w-full rounded-md border bg-neutral-800 px-3 py-2 text-sm text-ink-default placeholder:text-ink-subtle border-neutral-600" id="cs-required" type="text" placeholder="Acme Inc" required=""/>
        
      </div>
        </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Badge / Chip</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Five semantic variants, with an optional leading dot.</p>
            <div className="flex flex-wrap items-center gap-2">
          <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 ">Active</span>
          <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-warning-600 text-neutral-900 ">Pending</span>
          <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-danger-600 text-neutral-900 ">Failed</span>
          <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-info-600 text-neutral-900 ">Syncing</span>
          <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-neutral-700 text-ink-muted ">Draft</span>
          <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-neutral-700 text-ink-muted "><span className="h-1.5 w-1.5 rounded-full bg-primary-900"></span>With dot</span>
        </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Card</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Elevated and outlined, sharing one radius and space scale.</p>
            <div className="grid gap-4 md:grid-cols-2">
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h4 className="font-heading text-base font-semibold text-ink-default">Elevated</h4>
            <p className="mt-2 text-sm text-ink-muted">Uses the system's shadow scale and the raised surface token.</p></article>
          <article className="rounded-lg border border-neutral-600 p-6"><h4 className="font-heading text-base font-semibold text-ink-default">Outlined</h4>
            <p className="mt-2 text-sm text-ink-muted">Same spacing and radius, no fill, a visible edge.</p></article>
        </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Alert</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Dismissible, four tones, icon and action slot.</p>
            <div className="flex flex-col gap-3">
          <div className="flex items-start gap-3 rounded-md border border-success-600 bg-neutral-800 p-4 " role="status">
        <svg className="mt-0.5 h-4 w-4 shrink-0 text-ink-muted" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1.4"/>
          <path d="M4 8.5l2.5 2.5L12 5.5" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Payment received</p>
          <p className="mt-1 text-sm text-ink-muted">Your invoice for this month has been settled.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-ink-subtle hover:bg-neutral-700" type="button" aria-label="Dismiss">✕</button>
      </div>
          <div className="flex items-start gap-3 rounded-md border border-warning-600 bg-neutral-800 p-4 " role="status">
        <svg className="mt-0.5 h-4 w-4 shrink-0 text-ink-muted" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1.4"/>
          <path d="M8 5v4M8 11.5h.01" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Card expiring</p>
          <p className="mt-1 text-sm text-ink-muted">Your card expires at the end of next month.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-ink-subtle hover:bg-neutral-700" type="button" aria-label="Dismiss">✕</button>
      </div>
          <div className="flex items-start gap-3 rounded-md border border-danger-600 bg-neutral-800 p-4 " role="status">
        <svg className="mt-0.5 h-4 w-4 shrink-0 text-ink-muted" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1.4"/>
          <path d="M6 6l4 4M10 6l-4 4" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Sync failed</p>
          <p className="mt-1 text-sm text-ink-muted">We could not reach the billing provider. Retrying.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-ink-subtle hover:bg-neutral-700" type="button" aria-label="Dismiss">✕</button>
      </div>
          <div className="flex items-start gap-3 rounded-md border border-info-600 bg-neutral-800 p-4 " role="status">
        <svg className="mt-0.5 h-4 w-4 shrink-0 text-ink-muted" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1.4"/>
          <path d="M8 7.5v4M8 5h.01" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Scheduled maintenance</p>
          <p className="mt-1 text-sm text-ink-muted">Read-only mode on Sunday, 02:00 to 04:00 UTC.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-ink-subtle hover:bg-neutral-700" type="button" aria-label="Dismiss">✕</button>
      </div>
        </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Avatar</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Three sizes, initials fallback and a stacked group.</p>
            <div className="flex flex-col gap-5">
          <div className="flex items-center gap-3">
            <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 h-8 w-8 text-xs" title="Amelia R.">AR</span>
            <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 h-10 w-10 text-sm" title="Amelia R.">AR</span>
            <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 h-14 w-14 text-base" title="Amelia R.">AR</span>
          </div>
          <div className="flex items-center">
            <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-10 w-10 text-sm" title="Amelia R.">AR</span>
          <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-10 w-10 text-sm -ml-2" title="Thabo K.">TK</span>
          <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-10 w-10 text-sm -ml-2" title="Marta S.">MS</span>
          <span className="inline-flex items-center justify-center rounded-full bg-primary-900 font-heading text-neutral-900 border-2 border-neutral-900 h-10 w-10 text-sm -ml-2" title="Jonas B.">JB</span>
          <span className="-ml-2 inline-flex h-10 w-10 text-sm items-center justify-center rounded-full border-2 border-neutral-900 bg-neutral-700 text-ink-muted">+6</span>
          </div>
        </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Data Table</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Badge cells, monospace identifiers and a footer.</p>
            <div className="overflow-hidden rounded-lg border border-neutral-700">
        <table className="w-full border-collapse">
          <caption className="sr-only">Recent invoices</caption>
          <thead className="bg-neutral-800">
            <tr>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Invoice</th>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Customer</th>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Amount</th>
              <th className="px-4 py-2 text-left text-xs font-medium text-ink-subtle" scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">INV-2041</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Northwind Ltd</td>
              <td className="px-4 py-3 text-sm text-ink-muted">$4,800</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Paid</span></td>
            </tr>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">INV-2040</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Kestrel Group</td>
              <td className="px-4 py-3 text-sm text-ink-muted">$1,250</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-warning-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Pending</span></td>
            </tr>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">INV-2039</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Arbor Systems</td>
              <td className="px-4 py-3 text-sm text-ink-muted">$9,400</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-danger-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Failed</span></td>
            </tr>
            <tr className="border-t border-neutral-700">
              <td className="px-4 py-3 text-sm text-ink-muted font-mono text-ink-default">INV-2038</td>
              <td className="px-4 py-3 text-sm text-ink-muted">Vela Digital</td>
              <td className="px-4 py-3 text-sm text-ink-muted">$640</td>
              <td className="px-4 py-3 text-sm text-ink-muted"><span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-info-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Syncing</span></td>
            </tr>
          </tbody>
        </table>
      </div></article>
          <article className="rounded-lg border border-neutral-700 bg-neutral-800 shadow-md p-6"><h3 className="font-heading text-base font-semibold text-ink-default">Toast</h3>
            <p className="mb-5 mt-1 text-sm text-ink-muted">Stacked snackbars with an action.</p>
            <div className="flex flex-col gap-3">
          <div className="flex items-center gap-3 rounded-md border border-success-600 bg-neutral-800 p-4 shadow-lg">
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Changes saved</p>
          <p className="mt-0.5 text-xs text-ink-muted">Your settings are live.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-primary-900 hover:bg-neutral-700" type="button">Undo</button>
      </div>
          <div className="flex items-center gap-3 rounded-md border border-danger-600 bg-neutral-800 p-4 shadow-lg">
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">Upload failed</p>
          <p className="mt-0.5 text-xs text-ink-muted">The file was larger than 25 MB.</p>
        </div>
        <button className="shrink-0 rounded-md px-2 py-1 text-xs text-primary-900 hover:bg-neutral-700" type="button">Retry</button>
      </div>
          <div className="flex items-center gap-3 rounded-md border border-info-600 bg-neutral-800 p-4 shadow-lg">
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-ink-default">New version ready</p>
          <p className="mt-0.5 text-xs text-ink-muted">Refresh to update.</p>
        </div>
        
      </div>
        </div></article>
        </div>
      </section>
      
      <footer className="border-t border-neutral-700 bg-neutral-800">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-6 py-10 md:flex-row">
          <div className="font-heading text-primary-900 text-lg font-bold">Arena Rank</div>
          <p className="text-ink-subtle text-sm">Competitive coaching · built with DesignOps</p>
          <div className="flex gap-2">
            <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-neutral-700 text-ink-muted ">v2.0</span>
            <span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-medium bg-success-600 text-neutral-900 "><span className="h-1.5 w-1.5 rounded-full bg-neutral-900"></span>Live</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
