#!/usr/bin/env node
/**
 * DesignOps · token ship tool
 * ─────────────────────────────────────────────────────────────
 * Reads the single source of truth (tokens/tokens.json, W3C
 * Design Tokens format as exported from Figma Variables) and
 * emits ready-to-consume artifacts for every target:
 *
 *   dist/tokens.css          CSS custom properties (any stack)
 *   dist/tokens.scss         Sass variables
 *   dist/tokens.ts           TypeScript constants + types
 *   dist/tokens.tailwind.js  Tailwind preset
 *   dist/manifest.json       Build manifest (version, hash, count)
 *
 * The one rule of the whole system:
 *   Figma:  color/primary/900
 *   JSON:   color.primary.900
 *   CSS:    --color-primary-900        ("." and "/" become "-")
 *   TS:     colorPrimary900
 * Nothing else changes. Names never drift.
 *
 * Usage:
 *   node tools/ship.mjs            build everything into dist/
 *   node tools/ship.mjs --check    verify only (used by CI)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'tokens', 'tokens.json');
const OUT = join(root, 'dist');
const CHECK_ONLY = process.argv.includes('--check');

/* ── 1 · Flatten the W3C token tree into a flat map ─────────── */
function flatten(node, path = [], out = []) {
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith('$')) continue;               // skip $meta / $schema
    if (val && typeof val === 'object' && '$value' in val) {
      out.push({ path: [...path, key], value: val.$value, type: val.$type, desc: val.$description || '' });
    } else if (val && typeof val === 'object') {
      flatten(val, [...path, key], out);
    }
  }
  return out;
}

/* ── 2 · Name derivations (the single naming rule) ──────────── */
const cssName  = (t) => '--' + t.path.join('-');
const scssName = (t) => '$'  + t.path.join('-');
const tsName   = (t) => t.path.map((s, i) => (i ? s[0].toUpperCase() + s.slice(1) : s)).join('');
const figmaRef = (t) => t.path.join('/');

/* Tailwind theme sections a token can land in. */
const TW_GROUPS = {
  color: 'colors', space: 'spacing', radius: 'borderRadius',
  typography: 'fontSize', shadow: 'boxShadow', motion: 'transitionDuration', font: 'fontWeight',
};
function twSection(t) {
  if (t.path[0] === 'typography') return t.path[1] === 'weight' ? 'fontWeight' : 'fontSize';
  if (t.path[0] === 'motion')     return t.path[1] === 'easing' ? 'transitionTimingFunction' : 'transitionDuration';
  return TW_GROUPS[t.path[0]] || 'colors';
}
const twKey = (t) => t.path.slice(t.path[0] === 'typography' || t.path[0] === 'motion' ? 2 : 1).join('-');

/* ── 3 · Load + build all artifacts ─────────────────────────── */
const banner = (label) =>
  `/* ──────────────────────────────────────────────────────────
 * ${label}
 * AUTO-GENERATED by tools/ship.mjs — do not edit by hand.
 * Source of truth: tokens/tokens.json (export of Figma Variables)
 * ────────────────────────────────────────────────────────── */\n`;

const raw  = readFileSync(SRC, 'utf8');
const json = JSON.parse(raw);
const toks = flatten(json);

const css = banner(`Design tokens · CSS custom properties · ${toks.length} tokens`) +
`\n:root {\n${toks.map(t =>
  `  ${cssName(t)}: ${t.value};${t.desc ? ` /* ${t.desc} */` : ''}`).join('\n')}\n}\n`;

const scss = banner(`Design tokens · Sass variables · ${toks.length} tokens`).replace(/^\/\*/m, '// AUTO-GENERATED — see tokens.css for the banner legend\n/*') +
`\n${toks.map(t => `${scssName(t)}: ${t.value};`).join('\n')}\n`;

const ts = banner('Design tokens · TypeScript constants') +
`\nexport const tokens = {\n${toks.map(t =>
  `  /** ${figmaRef(t)} */\n  ${tsName(t)}: '${t.value}',`).join('\n')}\n} as const;\n
export type TokenName = keyof typeof tokens;
export const figmaRef = (name: TokenName) => name;\n`;

/* Tailwind preset: one canonical key per token per theme section. */
const preset = {};
for (const t of toks) {
  const section = twSection(t);
  (preset[section] ??= {})[twKey(t)] = t.value;
}
const tailwind = banner('Design tokens · Tailwind preset') +
`\n/** Use:  export default { presets: [require('./tokens.tailwind.js')], ... } */\n` +
`module.exports = ${JSON.stringify({ theme: { extend: preset } }, null, 2)};\n`;

/* Note: no timestamps here — output must be byte-reproducible so that
   `npm run verify` (the CI freshness gate) can diff deterministically. */
const manifest = JSON.stringify({
  name: 'designops-tokens',
  version: '3.0.0',
  tokenCount: toks.length,
  /** Short hash so apps can fail fast on stale token bundles. */
  hash: createHash('sha1').update(raw).digest('hex').slice(0, 10),
  targets: ['css', 'scss', 'typescript', 'tailwind-preset', 'manifest'],
}, null, 2) + '\n';

/* ── 4 · Write (or verify) ──────────────────────────────────── */
const files = {
  'tokens.css': css,
  'tokens.scss': scss,
  'tokens.ts': ts,
  'tokens.tailwind.js': tailwind,
  'manifest.json': manifest,
};

mkdirSync(OUT, { recursive: true });
for (const [file, content] of Object.entries(files)) {
  const dest = join(OUT, file);
  if (CHECK_ONLY) {
    let current = '';
    try { current = readFileSync(dest, 'utf8'); } catch { /* missing */ }
    if (current !== content) {
      console.error(`✗ ${file} is stale — run \`npm run build:tokens\``);
      process.exit(1);
    }
  } else {
    writeFileSync(dest, content);
    console.log(`✓ shipped ${file}`);
  }
}
console.log(CHECK_ONLY
  ? `✓ all ${toks.length} tokens up to date`
  : `\n${toks.length} tokens → ${Object.keys(files).length} artifacts in dist/`);
